paths:
  train:
  test: '${hydra:runtime.cwd}/tabular_src/test/testdata/adult_test.csv'
  output: "${hydra:runtime.cwd}/results"
  result: "${hydra:runtime.cwd}/results/lightgbm"

columns:
  categorical_columns: ['workclass', 'fnlwgt', 'education', 'marital.status', 'occupation', 'relationship',
                        'race', 'sex', 'native.country']
  text_columns:
  keep_columns:
  sensitive_columns: ['race', 'sex']
  target_label: 'income'
  drift_columns: []

process:
  exp_id: 'lightgbm'
  memory_reduce: True
  infer_datatype: True
  test_ratio: 0.2
  seed: 33
  task: 'classification'
  verbose: False
  surrogate_model: False
  only_surrogate: False

feature_selection:
  auto: True
  estimator: 'lightgbm'
  n_features: 9
  multi_colinear_threshold: 0.6

data_validation:
  data_drift: True
  data_integrity: True
  prediction_drift: True
  save_html: True

defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

model:
  surrogate_algorithm: 'random_forest'
  algorithm: ['lightgbm', 'catboost']
  ensemble: False
  ensemble_type: 'stack'
  cv_fold: 4
  iteration: 60
  prob_thresh: 0.5
  tuning: True
  pca: False
  calibrate: True
  feature_importance: False
  fairness: True

hyperparams:
  - lightgbm:
  - xgboost:
  - catboost:
  - dt:
  - logistic_regression:
  - linear_regession:
  - svm:
  - rf:
  - knn:
  - gbc:
