paths:
  train:
  test: '${hydra:runtime.cwd}/tabular_src/test/testdata/adult_test.csv'
  output: '${hydra:runtime.cwd}/results'
  result: '${hydra:runtime.cwd}/results/test'

columns:
  categorical_columns: ['workclass', 'fnlwgt', 'education', 'marital.status', 'occupation', 'relationship',
                        'race', 'sex', 'native.country']
  text_columns:
  keep_columns: ['race', 'sex']
  sensitive_columns: ['race', 'sex']
  target_label: 'income'
  monotonic_increase_columns: ['education.num', 'hours.per.week']
  monotonic_decrease_columns:
  drift_columns: ['education', 'marital.status', 'occupation', 'race', 'hours.per.week']

process:
  exp_id: 'test'
  memory_reduce: True
  infer_datatype: True
  test_ratio: 0.2
  seed: 33
  task: 'classification'
  verbose: False
  surrogate_model: True
  only_surrogate: False

feature_selection:
  auto: True
  estimator: 'lightgbm'
  n_features: 0.9
  multi_colinear_threshold: 0.6

data_validation:
  data_drift: True
  data_integrity: True
  prediction_drift: True
  save_html: True

defaults:
  - _self_
  - hydra/hydra_logging: none
  - hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

model:
  surrogate_algorithm: 'random_forest'
  algorithm: ['catboost', 'xgboost', 'lightgbm']
  ensemble: False
  ensemble_type: 'stack'
  cv_fold: 4
  iteration: 60
  prob_thresh: 0.5
  tuning: True
  pca: False
  calibrate: True
  feature_importance: True
  fairness: True

hyperparams:
  classification_params: '${hydra:runtime.cwd}/config/hyper_params_classification.yaml'
  regression_params: '${hydra:runtime.cwd}/config/hyper_params_regression.yaml'
